# -*- coding: utf-8 -*-
"""keluarga.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lOmlnjQVCIAh2MJDUy8C5Z09XP1BGnMR
"""

from abc import abstractmethod, ABC

class keluarga(ABC):
    def cetak():
        print("Pekerjaan Keluarga")

    
    @abstractmethod
    def tugas(self):
        pass
    
class ayah(keluarga):
    def tugas(self):
        print("ayah sedang beri makan hewan")
        
class ibu(keluarga):
    def tugas(self):
        print("ibu sedang memasak")

class anak(keluarga):
    def tugas(self, a, b):
      hasil = a+b
      print("anak belajar pertambahan "+str(a)+"+"+str(b)+" =", hasil)

