# -*- coding: utf-8 -*-
"""KTM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lOmlnjQVCIAh2MJDUy8C5Z09XP1BGnMR
"""

class KTM(object):
    
    def __init__(selfie, input_nim, input_nama, input_usia, input_fakultas, input_jurusan):
        selfie.nim = input_nim
        selfie.nama = input_nama
        selfie.usia = input_usia
        selfie.fakultas = input_fakultas
        selfie.jurusan = input_jurusan
        

        
    def display(selfie):
        print(selfie.nim)
        print(selfie.nama)
        print(selfie.usia)
        print(selfie.fakultas)
        print(selfie.jurusan)

    def info(selfie):
        print(f"NIM: {selfie.nim}, Nama: {selfie.nama}, Usia: {selfie.usia}, Fakultas: {selfie.fakultas}, Jurusan: {selfie.jurusan}")


info_ktm = KTM(672018187, "timothy", 19, "Teknik Informasi", "Teknik Informatika")