# -*- coding: utf-8 -*-
"""pajak.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lOmlnjQVCIAh2MJDUy8C5Z09XP1BGnMR
"""

class cek_pajak(object):
    def __init__(selfie, nama, usia):
        selfie.nama = nama
        selfie.usia = usia


    def kecukupan(selfie, umur):
        if(umur < 20):
            print("Belum membayar pajak")
        else:
          print("Bayar Pajak")

    def info(selfie):
        print(f"nama: {selfie.nama}, usia: {selfie.usia}")


Kartu = cek_pajak("Timothy", 19)

class KTP(cek_pajak):
    def __init__(selfie, nomor, nama, usia, tempat_lahir):
        super().__init__(nama, usia)
        selfie.nomor = nomor
        selfie.tempat_lahir = tempat_lahir

    def cukup(selfie):
        super().kecukupan(selfie.usia)
        print("........")

    def info_ktp(selfie):
        super().info()
        print(f"No KTP: {selfie.nomor}, Tempat Lahir: {selfie.tempat_lahir}")

ktp = KTP(123456789, "Garry", 20, "Manado")

class SIM(cek_pajak):
    def __init__(selfie, nama, usia, kelamin, jenis):
        super().__init__(nama, usia)
        selfie.gender = kelamin
        selfie.jenis_sim = jenis

    def cukup(selfie):
        super().kecukupan(selfie.usia)
        print("SIM ",selfie.jenis_sim)

    def info_sim(selfie):
        super().info()
        print(f"Jenis Kelamin: {selfie.gender}, Kriteria SIM: {selfie.jenis_sim}")

sim = SIM("gelyen", 19, "Pria", "A")

class KTM(cek_pajak):
    def __init__(selfie, nim, nama, usia, fakultas, jurusan):
        super().__init__(nama, usia)
        selfie.nim = nim
        selfie.fakultas = fakultas
        selfie.jurusan = jurusan

    def cukup(selfie):
        super().kecukupan(selfie.usia)
        print(selfie.fakultas, "" , selfie.jurusan)

    def info_ktm(selfie):
        super().info()
        print(f"nim: {selfie.nim}, fakultas: {selfie.fakultas}, jurusan: {selfie.jurusan}")

ktm = KTM(672018187,"astaroth", 21, "FTI", "Teknik Informatika")

