# -*- coding: utf-8 -*-
"""pegawai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lOmlnjQVCIAh2MJDUy8C5Z09XP1BGnMR
"""

class Pegawai(object):
  def __init__(self, nama, usia, nip, gelar):
    self.nip = nip
    self.nama = nama
    self.usia = usia
    self.gelar = gelar

  def kerja(self, durasi):
      print("Lama waktu kerja "+ str(durasi)+" Jam")

  def info(self):
    print(f"Nip: {self.nip}, nama: {self.nama}, usia: {self.usia}, gelar: {self.gelar}")


class pns(Pegawai):
  def __init__(self, nip, nama, usia, gelar, eselon, penempatan, organisasi):
    super().__init__(nip, nama, usia, gelar)
    self.eselon = eselon
    self.penempatan = penempatan
    self.organisasi = organisasi
  
  def masuk_kerja(self, durasi):
    for x in range(durasi):
      print("jam")
      print(durasi)

  def info_pns(self):
    print(f"Eselon: {self.eselon}, Bidang tempat: {self.penempatan}, Struktur sebagai: {self.organisasi}")

class honorer(Pegawai):
  def __init__(self, nip, nama, usia, gelar, kategori):
    super().__init__(nip, nama, usia, gelar)
    self.kategori = kategori  

  def lama_kerja(self, waktu):
    if waktu >=6 :
      print("Gaji anda tidak terpotong")
    else:
      print("Gaji terpotong")